import { beforeEach, describe, expect, it } from 'vitest'
import { defaultExerciseConfig } from '../exercise/types'
import { completeSessionAssignment, createSessionAssignment, createTreatmentCycle, listSessionAssignments, listTreatmentCycles, sessionDurationSeconds, startSessionAssignment } from './repository'
import { clearPendingSessionCompletions, isLikelyNetworkFailure, pendingSessionCompletionCount, queueSessionCompletion } from './offlineQueue'

describe('repositorio demo de ciclos y sesiones',()=>{
  beforeEach(()=>localStorage.clear())
  it('crea un ciclo activo para un paciente',async()=>{const created=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'Objetivo',startedOn:'2026-07-16'});expect(created.status).toBe('active');expect(await listTreatmentCycles('patient-new')).toHaveLength(1)})
  it('conserva la configuración de ejercicios en la asignación',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Sesión inicial',instructions:'Indicaciones',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[{...defaultExerciseConfig,durationSeconds:30,rounds:2,restSeconds:10}]});expect((await listSessionAssignments('patient-new'))[0].exercises[0].durationSeconds).toBe(30);expect(sessionDurationSeconds(assignment)).toBe(70)})
  it('guarda el auto-reporte descriptivo al finalizar',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Sesión inicial',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});await completeSessionAssignment({assignment,activeSeconds:42.4,skippedExercises:1,initialDiscomfort:3,finalDiscomfort:4,perceivedDifficulty:2,patientComment:'  Todo bien  '});const saved=(await listSessionAssignments('patient-new'))[0];expect(saved).toMatchObject({status:'partial',activeSeconds:42,initialDiscomfort:3,finalDiscomfort:4,perceivedDifficulty:2,patientComment:'Todo bien'})})
  it('registra el inicio sin impedir que la sesión pueda retomarse',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Sesión inicial',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});await startSessionAssignment(assignment);expect((await listSessionAssignments('patient-new'))[0].status).toBe('started')})
  it('mantiene una sola finalización pendiente por asignación',async()=>{const cycle=await createTreatmentCycle('patient-new',{label:'Ciclo 1',reason:'',objectives:'',startedOn:'2026-07-16'});const assignment=await createSessionAssignment('patient-new',{title:'Sesión inicial',instructions:'',mode:'home',treatmentCycleId:cycle.id,availableFrom:'2026-07-16',availableUntil:'',exercises:[defaultExerciseConfig]});const input={assignment,activeSeconds:20,skippedExercises:0,initialDiscomfort:1,finalDiscomfort:1,perceivedDifficulty:2,patientComment:''};queueSessionCompletion(input);queueSessionCompletion({...input,activeSeconds:25});expect(pendingSessionCompletionCount()).toBe(1);clearPendingSessionCompletions();expect(pendingSessionCompletionCount()).toBe(0)})
  it('distingue una caída de red de un error de autorización',()=>{expect(isLikelyNetworkFailure(new TypeError('Failed to fetch'))).toBe(true);expect(isLikelyNetworkFailure(new Error('Asignación no disponible.'))).toBe(false)})
})
