import { AlertTriangle, ChevronLeft, FileUp, ShieldCheck, UploadCloud } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { useUploadDocument } from '../features/documents/hooks'
import { documentTypeLabels, type ClinicalDocumentType } from '../features/documents/types'
import { usePatients } from '../features/patients/hooks'
import { useTreatmentCycles } from '../features/sessions/hooks'
import { isSupabaseConfigured } from '../lib/supabase'

export function ImportStudyPage(){
  const[params]=useSearchParams();const navigate=useNavigate();const{data:patients=[]}=usePatients();const[patientId,setPatientId]=useState(params.get('patient')??'');const{data:cycles=[]}=useTreatmentCycles(patientId);const upload=useUploadDocument(patientId)
  const[type,setType]=useState<ClinicalDocumentType>('posturography');const[cycleId,setCycleId]=useState('');const[date,setDate]=useState(new Date().toISOString().slice(0,10));const[description,setDescription]=useState('');const[share,setShare]=useState(false);const[file,setFile]=useState<File|null>(null);const[device,setDevice]=useState('');const[protocol,setProtocol]=useState('bap-a-d');const[protocolVersion,setProtocolVersion]=useState('1');const[error,setError]=useState('')
  const isStudy=type==='posturography'||type==='vhit'
  useEffect(()=>{const active=cycles.find(cycle=>cycle.status==='active');setCycleId(active?.id??'')},[cycles])
  useEffect(()=>{if(type==='posturography')setProtocol('bap-a-d');else if(type==='vhit')setProtocol('vhit-bilateral');else setProtocol('')},[type])
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!patientId){setError('Seleccioná un paciente.');return}if(!file){setError('Seleccioná el archivo original.');return}if(!date){setError('Indicá la fecha del documento.');return}if(isStudy&&(!protocol||!protocolVersion.trim())){setError('Seleccioná el protocolo e indicá su versión.');return}setError('');try{const result=await upload.mutateAsync({patientId,treatmentCycleId:cycleId,documentType:type,documentDate:date,description,shareWithPatient:share,file,deviceName:device,protocolCode:protocol,protocolVersion});const permissionWarning=share&&!result.sharedWithPatient?' El archivo quedó privado porque no se pudo habilitar el permiso solicitado.':'';if(isStudy&&result.studyId)navigate(`/app/estudios/${result.studyId}/revisar`,{state:{notice:`Documento original cargado.${permissionWarning}`}});else navigate(`/app/pacientes/${patientId}`,{state:{notice:`Documento cargado correctamente.${permissionWarning}`}})}catch(caught){setError(caught instanceof Error?caught.message:'No fue posible cargar el documento.')}}
  const input='mt-2 h-12 w-full rounded-2xl border border-[#cfddda] bg-white px-4 text-sm text-[#17363c]'
  return <div className="space-y-7"><Link to={patientId?`/app/pacientes/${patientId}`:'/app'} className="inline-flex items-center gap-2 text-xs font-black text-[#0b7a75]"><ChevronLeft size={16}/> Volver</Link><PageHeader eyebrow="Documentos clínicos" title="Cargar documento o estudio" description="El original se conserva en almacenamiento privado y solo se comparte mediante permiso explícito."/>
    <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><section className="space-y-5 rounded-3xl border border-[#dce7e5] bg-white p-6 sm:p-7"><div className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#e8f5f2] text-[#08746e]"><UploadCloud size={21}/></span><div><h2 className="text-lg font-black text-[#123238]">Identificación del archivo</h2><p className="mt-1 text-xs leading-5 text-[#60777d]">Posturografías, vHIT, cuestionarios fotografiados e informes.</p></div></div>
      <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-black text-[#29474d]">Paciente *<select className={input} value={patientId} onChange={event=>setPatientId(event.target.value)}><option value="">Seleccionar…</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.fullName}</option>)}</select></label><label className="text-sm font-black text-[#29474d]">Ciclo<select className={input} value={cycleId} onChange={event=>setCycleId(event.target.value)}><option value="">Sin asociar</option>{cycles.map(cycle=><option key={cycle.id} value={cycle.id}>{cycle.label} · {cycle.status}</option>)}</select></label><label className="text-sm font-black text-[#29474d]">Tipo *<select className={input} value={type} onChange={event=>setType(event.target.value as ClinicalDocumentType)}>{Object.entries(documentTypeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-black text-[#29474d]">Fecha del documento *<input type="date" className={input} value={date} onChange={event=>setDate(event.target.value)}/></label></div>
      <label className="block text-sm font-black text-[#29474d]">Descripción<textarea className="mt-2 min-h-24 w-full rounded-2xl border border-[#cfddda] p-4 text-sm" value={description} onChange={event=>setDescription(event.target.value)} placeholder="Contexto o identificación breve, sin interpretar resultados."/></label>
      {isStudy&&<div className="grid gap-5 rounded-2xl bg-[#f5f8f7] p-5 sm:grid-cols-3"><label className="text-xs font-black text-[#29474d]">Equipo / sistema<input className={input} value={device} onChange={event=>setDevice(event.target.value)}/></label><label className="text-xs font-black text-[#29474d]">Protocolo *<select className={input} value={protocol} onChange={event=>setProtocol(event.target.value)}>{type==='posturography'?<><option value="bap-a-d">bAp · condiciones A–D</option><option value="bap-1-6">bAp · condiciones 1–6</option><option value="manual-posturography">Otro / transcripción manual</option></>:<><option value="vhit-bilateral">vHIT bilateral</option><option value="manual-vhit">Otro / transcripción manual</option></>}</select></label><label className="text-xs font-black text-[#29474d]">Versión *<input className={input} value={protocolVersion} onChange={event=>setProtocolVersion(event.target.value)}/></label></div>}
      <label className="grid min-h-44 cursor-pointer place-items-center rounded-3xl border-2 border-dashed border-[#b9d2ce] bg-[#f8fbfa] p-6 text-center"><span><FileUp className="mx-auto text-[#0b7a75]" size={28}/><strong className="mt-3 block text-sm text-[#29474d]">{file?file.name:'Seleccionar archivo original'}</strong><span className="mt-1 block text-xs text-[#71878c]">PDF, JPG, PNG, WEBP, XLS o XLSX · máximo 25 MB</span>{file&&<span className="mt-2 block text-xs font-bold text-[#0b7a75]">{(file.size/1024/1024).toFixed(2)} MB</span>}</span><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.xls,.xlsx" className="sr-only" onChange={event=>setFile(event.target.files?.[0]??null)}/></label>
    </section><aside className="space-y-5"><section className="rounded-3xl border border-[#dce7e5] bg-white p-6"><ShieldCheck className="text-[#0b7a75]" size={24}/><h2 className="mt-4 font-black text-[#123238]">Permiso del paciente</h2><p className="mt-2 text-xs leading-5 text-[#60777d]">El documento permanece privado salvo que habilites su visualización.</p><label className="mt-5 flex items-start gap-3 rounded-2xl bg-[#f5f8f7] p-4 text-sm font-bold text-[#29474d]"><input type="checkbox" className="mt-1" checked={share} onChange={event=>setShare(event.target.checked)}/><span>Permitir que el paciente lo vea desde su cuenta<small className="mt-1 block font-normal text-[#71878c]">Activo hasta que el profesional lo revoque manualmente.</small></span></label></section>
      {!isSupabaseConfigured&&<div className="flex gap-3 rounded-3xl border border-[#f0d8a3] bg-[#fff6e4] p-5"><AlertTriangle className="shrink-0 text-[#98620b]" size={20}/><p className="text-xs leading-5 text-[#805b16]">En modo demo se conservan los metadatos, pero el archivo original no se sube.</p></div>}{error&&<p role="alert" className="rounded-2xl bg-[#fceced] p-4 text-sm font-bold text-[#a94952]">{error}</p>}<button disabled={upload.isPending} className="w-full rounded-2xl bg-[#0b7a75] px-5 py-4 text-sm font-black text-white">{upload.isPending?'Cargando y verificando…':isStudy?'Guardar y revisar valores':'Guardar documento'}</button></aside></form>
  </div>
}
