import { ChevronLeft, ShieldCheck } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { useCreatePatient, usePatient, useUpdatePatient } from '../features/patients/hooks'
import { patientFormSchema, suggestUsername, type PatientFormValues } from '../features/patients/schema'

const empty: PatientFormValues = { fullName:'', birthDate:'', insurer:'', affiliateNumber:'', phone:'', status:'active', privateNotes:'', createPortalAccount:false, username:'', temporaryCi:'' }

export function PatientFormPage() {
  const { patientId } = useParams(); const editing = Boolean(patientId); const navigate = useNavigate()
  const { data: patient } = usePatient(patientId ?? '')
  const create = useCreatePatient(); const update = useUpdatePatient(patientId ?? '')
  const [values,setValues]=useState(empty); const [errors,setErrors]=useState<Record<string,string>>({}); const [usernameTouched,setUsernameTouched]=useState(false)
  useEffect(()=>{ if(patient) setValues({ fullName:patient.fullName,birthDate:patient.birthDate,insurer:patient.insurer==='Sin mutualista'?'':patient.insurer,affiliateNumber:patient.affiliateNumber,phone:patient.phone,status:patient.status,privateNotes:patient.privateNotes,createPortalAccount:false,username:patient.username,temporaryCi:'' }) },[patient])
  const set = (key:keyof PatientFormValues,value:string|boolean)=>setValues((current)=>({...current,[key]:value}))
  const submit=async(e:FormEvent)=>{e.preventDefault();const parsed=patientFormSchema.safeParse(values);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(i=>[String(i.path[0]),i.message])));return}setErrors({});try{const result=editing?await update.mutateAsync(parsed.data):await create.mutateAsync(parsed.data);navigate(`/app/pacientes/${result.patient.id}`,{state:{notice:result.warning??(editing?'Paciente actualizado.':'Paciente creado correctamente.')}})}catch(caught){setErrors({form:caught instanceof Error?caught.message:'No fue posible guardar.'})}}
  const pending=create.isPending||update.isPending
  const input='mt-2 h-12 w-full rounded-2xl border border-[#cfddda] bg-white px-4 text-sm text-[#17363c]'
  return <div className="space-y-7"><Link to={editing?`/app/pacientes/${patientId}`:'/app/pacientes'} className="inline-flex items-center gap-2 text-xs font-black text-[#0b7a75]"><ChevronLeft size={16}/> Volver</Link><PageHeader eyebrow="Gestión clínica" title={editing?'Editar paciente':'Crear paciente'} description="Los datos privados quedan separados del acceso del paciente."/>
    <form onSubmit={submit} className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]"><section className="space-y-5 rounded-3xl border border-[#dce7e5] bg-white p-6"><h2 className="text-lg font-black text-[#123238]">Datos del paciente</h2>
      <label className="block text-sm font-black text-[#29474d]">Nombre completo *<input className={input} value={values.fullName} onChange={(e)=>{set('fullName',e.target.value);if(!usernameTouched)set('username',suggestUsername(e.target.value))}}/>{errors.fullName&&<small className="mt-1 block text-[#a94952]">{errors.fullName}</small>}</label>
      <div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-black text-[#29474d]">Fecha de nacimiento<input type="date" className={input} value={values.birthDate} onChange={(e)=>set('birthDate',e.target.value)}/>{errors.birthDate&&<small className="text-[#a94952]">{errors.birthDate}</small>}</label><label className="block text-sm font-black text-[#29474d]">Mutualista<input className={input} value={values.insurer} onChange={(e)=>set('insurer',e.target.value)}/></label><label className="block text-sm font-black text-[#29474d]">N.º de afiliado<input className={input} value={values.affiliateNumber} onChange={(e)=>set('affiliateNumber',e.target.value)}/></label><label className="block text-sm font-black text-[#29474d]">Teléfono<input className={input} value={values.phone} onChange={(e)=>set('phone',e.target.value)}/></label></div>
      <label className="block text-sm font-black text-[#29474d]">Notas privadas<textarea className="mt-2 min-h-28 w-full rounded-2xl border border-[#cfddda] p-4 text-sm" value={values.privateNotes} onChange={(e)=>set('privateNotes',e.target.value)}/><small className="mt-1 block font-normal text-[#71878c]">Nunca se muestran en el portal del paciente.</small></label>
      {editing&&<label className="block text-sm font-black text-[#29474d]">Estado<select className={input} value={values.status} onChange={(e)=>set('status',e.target.value)}><option value="active">Activo</option><option value="inactive">Inactivo</option></select></label>}
    </section><aside className="space-y-5"><section className="rounded-3xl border border-[#dce7e5] bg-white p-6"><div className="flex gap-3"><ShieldCheck className="text-[#0b7a75]"/><div><h2 className="font-black text-[#123238]">Acceso al portal</h2><p className="mt-1 text-xs leading-5 text-[#60777d]">La cédula se usa solo como clave temporal y no se almacena.</p></div></div>{!editing&&<><label className="mt-5 flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={values.createPortalAccount} onChange={(e)=>set('createPortalAccount',e.target.checked)}/> Crear cuenta ahora</label>{values.createPortalAccount&&<div className="mt-5 space-y-4"><label className="block text-sm font-black text-[#29474d]">Usuario<input className={input} value={values.username} onChange={(e)=>{setUsernameTouched(true);set('username',e.target.value)}}/>{errors.username&&<small className="text-[#a94952]">{errors.username}</small>}</label><label className="block text-sm font-black text-[#29474d]">Cédula temporal<input className={input} type="password" inputMode="numeric" value={values.temporaryCi} onChange={(e)=>set('temporaryCi',e.target.value.replace(/\D/g,''))}/>{errors.temporaryCi&&<small className="text-[#a94952]">{errors.temporaryCi}</small>}</label><p className="rounded-2xl bg-[#fff5dd] p-3 text-xs leading-5 text-[#715a22]">En el primer acceso deberá reemplazarla por un PIN de 4 dígitos.</p></div>}</>}</section>
      {errors.form&&<p role="alert" className="rounded-2xl bg-[#fceced] p-4 text-sm font-bold text-[#a94952]">{errors.form}</p>}<button disabled={pending} className="w-full rounded-2xl bg-[#0b7a75] px-5 py-4 text-sm font-black text-white disabled:opacity-60">{pending?'Guardando…':editing?'Guardar cambios':'Crear paciente'}</button></aside></form></div>
}
