import { ArrowDown, ArrowUp, ChevronLeft, Copy, Plus, Save, Trash2 } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { defaultExerciseConfig, type ExerciseConfig } from '../features/exercise/types'
import { usePatient } from '../features/patients/hooks'
import { useCreateSessionAssignment, useTreatmentCycles } from '../features/sessions/hooks'
import { SessionExerciseEditor } from '../features/sessions/SessionExerciseEditor'
import { validateSession, type SessionFormValues } from '../features/sessions/schema'
import { useExerciseTemplates } from '../features/templates/hooks'

export function SessionBuilderPage(){
  const{patientId=''}=useParams();const navigate=useNavigate();const{data:patient}=usePatient(patientId);const{data:cycles=[]}=useTreatmentCycles(patientId);const create=useCreateSessionAssignment(patientId);const[selected,setSelected]=useState(0);const[errors,setErrors]=useState<Record<string,string>>({})
  const { data: templates = [] } = useExerciseTemplates()
  const[values,setValues]=useState<SessionFormValues>({title:'Sesión vestíbulo-visual',instructions:'Realizar según las indicaciones brindadas por el profesional.',mode:'home',treatmentCycleId:'',availableFrom:new Date().toISOString().slice(0,10),availableUntil:'',exercises:[{...defaultExerciseConfig}]})
  useEffect(()=>{const active=cycles.find(c=>c.status==='active');if(active&&!values.treatmentCycleId)setValues(v=>({...v,treatmentCycleId:active.id}))},[cycles,values.treatmentCycleId])
  const updateExercise=(config:ExerciseConfig)=>setValues(v=>({...v,exercises:v.exercises.map((e,i)=>i===selected?config:e)}));const move=(direction:-1|1)=>{const target=selected+direction;if(target<0||target>=values.exercises.length)return;setValues(v=>{const next=[...v.exercises];[next[selected],next[target]]=[next[target],next[selected]];return{...v,exercises:next}});setSelected(target)}
  const submit=async(event:FormEvent)=>{event.preventDefault();const found=validateSession(values);setErrors(found);if(Object.keys(found).length)return;try{await create.mutateAsync(values);navigate(`/app/pacientes/${patientId}`,{state:{notice:'Sesión creada y asignada correctamente.'}})}catch(caught){setErrors({form:caught instanceof Error?caught.message:'No fue posible crear la sesión.'})}}
  const input='mt-2 h-11 w-full rounded-2xl border border-[#cfddda] bg-white px-3 text-sm'
  return <div className="space-y-7"><Link to={`/app/pacientes/${patientId}`} className="inline-flex items-center gap-2 text-xs font-black text-[#0b7a75]"><ChevronLeft size={16}/> Volver al perfil</Link><PageHeader eyebrow="Planificación" title="Crear y asignar sesión" description={patient?`Configuración para ${patient.fullName}. Cada ejercicio mantiene fondo y objeto independientes.`:'Prepará una sesión.'}/>
    {cycles.length===0?<section className="rounded-3xl border border-[#f0d8a3] bg-[#fff6e4] p-6"><h2 className="font-black text-[#805b16]">Primero necesitás un ciclo activo</h2><p className="mt-2 text-sm text-[#805b16]">Las sesiones quedan asociadas al ciclo para conservar el historial y preparar el informe final.</p><Link to={`/app/pacientes/${patientId}/ciclos/nuevo`} className="mt-4 inline-flex rounded-2xl bg-[#98620b] px-4 py-3 text-sm font-black text-white">Iniciar ciclo</Link></section>:<form onSubmit={submit} className="space-y-7"><section className="grid gap-5 rounded-3xl border border-[#dce7e5] bg-white p-6 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-black text-[#29474d] xl:col-span-2">Título<input className={input} value={values.title} onChange={e=>setValues(v=>({...v,title:e.target.value}))}/>{errors.title&&<small className="text-[#a94952]">{errors.title}</small>}</label><label className="text-xs font-black text-[#29474d]">Modalidad<select className={input} value={values.mode} onChange={e=>setValues(v=>({...v,mode:e.target.value as SessionFormValues['mode']}))}><option value="home">Domiciliaria</option><option value="in_person">Presencial</option></select></label><label className="text-xs font-black text-[#29474d]">Ciclo<select className={input} value={values.treatmentCycleId} onChange={e=>setValues(v=>({...v,treatmentCycleId:e.target.value}))}>{cycles.filter(c=>c.status!=='completed').map(c=><option key={c.id} value={c.id}>{c.label} · {c.status}</option>)}</select></label><label className="text-xs font-black text-[#29474d]">Disponible desde<input type="date" className={input} value={values.availableFrom} onChange={e=>setValues(v=>({...v,availableFrom:e.target.value}))}/></label><label className="text-xs font-black text-[#29474d]">Disponible hasta (opcional)<input type="date" className={input} value={values.availableUntil} onChange={e=>setValues(v=>({...v,availableUntil:e.target.value}))}/></label><label className="text-xs font-black text-[#29474d] md:col-span-2">Indicaciones para el paciente<textarea className="mt-2 min-h-20 w-full rounded-2xl border border-[#cfddda] p-3 text-sm" value={values.instructions} onChange={e=>setValues(v=>({...v,instructions:e.target.value}))}/></label></section>
      <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-[#123238]">Ejercicios</h2><p className="mt-1 text-xs text-[#71878c]">Se reproducen en este orden con continuación automática.</p></div><div className="flex gap-2"><select defaultValue="" onChange={event=>{const template=templates.find(item=>item.id===event.target.value);if(template){setValues(v=>({...v,exercises:[...v.exercises,{...template.config}]}));setSelected(values.exercises.length)}event.target.value=''}} className="rounded-2xl border border-[#cfddda] bg-white px-3 text-xs font-black text-[#29474d]"><option value="">Agregar desde biblioteca…</option>{templates.map(template=><option key={template.id} value={template.id}>{template.name}</option>)}</select><button type="button" onClick={()=>{setValues(v=>({...v,exercises:[...v.exercises,{...defaultExerciseConfig,name:`Ejercicio ${v.exercises.length+1}`}]}));setSelected(values.exercises.length)}} className="inline-flex items-center gap-2 rounded-2xl border border-[#cfddda] bg-white px-4 py-3 text-xs font-black text-[#29474d]"><Plus size={16}/> Nuevo</button></div></div><div className="mb-5 flex gap-3 overflow-x-auto pb-2">{values.exercises.map((exercise,index)=><button key={index} type="button" onClick={()=>setSelected(index)} className={`min-w-48 rounded-2xl border p-4 text-left ${selected===index?'border-[#0b7a75] bg-[#e8f5f2]':'border-[#dce7e5] bg-white'}`}><span className="text-[10px] font-black uppercase text-[#0b7a75]">Ejercicio {index+1}</span><p className="mt-2 truncate text-sm font-black text-[#29474d]">{exercise.name}</p><p className="mt-1 text-xs text-[#71878c]">{exercise.durationSeconds}s × {exercise.rounds}</p></button>)}</div><div className="mb-4 flex gap-2"><button type="button" onClick={()=>move(-1)} className="rounded-xl border border-[#cfddda] p-2" aria-label="Mover antes"><ArrowUp size={16}/></button><button type="button" onClick={()=>move(1)} className="rounded-xl border border-[#cfddda] p-2" aria-label="Mover después"><ArrowDown size={16}/></button><button type="button" onClick={()=>setValues(v=>({...v,exercises:[...v.exercises,{...v.exercises[selected],name:`${v.exercises[selected].name} (copia)`}]}))} className="rounded-xl border border-[#cfddda] p-2" aria-label="Duplicar"><Copy size={16}/></button><button type="button" disabled={values.exercises.length===1} onClick={()=>{setValues(v=>({...v,exercises:v.exercises.filter((_,i)=>i!==selected)}));setSelected(Math.max(0,selected-1))}} className="rounded-xl border border-[#eccfd2] p-2 text-[#a94952] disabled:opacity-30" aria-label="Eliminar"><Trash2 size={16}/></button></div>{errors.exercises&&<p className="mb-4 text-sm font-bold text-[#a94952]">{errors.exercises}</p>}<SessionExerciseEditor config={values.exercises[selected]} onChange={updateExercise}/></section>
      {errors.form&&<p role="alert" className="rounded-2xl bg-[#fceced] p-4 text-sm font-bold text-[#a94952]">{errors.form}</p>}<div className="sticky bottom-4 z-10 flex justify-end"><button disabled={create.isPending} className="inline-flex items-center gap-2 rounded-2xl bg-[#0b7a75] px-6 py-4 text-sm font-black text-white shadow-xl"><Save size={17}/>{create.isPending?'Asignando…':'Guardar y asignar sesión'}</button></div></form>}</div>
}
