import { BarChart3, CheckCircle2, ClipboardList, Clock3, Home, MonitorPlay, Users } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { StatCard } from '../components/StatCard'
import { useProfessionalAssessments } from '../features/assessments/hooks'
import { usePatients } from '../features/patients/hooks'
import { useProfessionalAssignments } from '../features/sessions/hooks'
import { buildProfessionalStatistics, type StatisticsPeriod } from '../features/statistics/analytics'

const statusLabels={completed:'Completadas',partial:'Parciales',assigned:'Asignadas',started:'Iniciadas',interrupted:'Interrumpidas',omitted:'Omitidas'} as const

export function StatisticsPage(){
  const[period,setPeriod]=useState<StatisticsPeriod>('all');const[patientId,setPatientId]=useState('')
  const{data:patients=[],isPending:patientsPending}=usePatients();const{data:assignments=[],isPending:sessionsPending}=useProfessionalAssignments();const{data:assessments=[],isPending:assessmentsPending}=useProfessionalAssessments()
  const statistics=useMemo(()=>buildProfessionalStatistics(assignments,assessments,patients,{period,patientId}),[assignments,assessments,patients,period,patientId]);const pending=patientsPending||sessionsPending||assessmentsPending
  const maxMonthly=Math.max(1,...statistics.activityByMonth.map(item=>item.assigned));const maxStatus=Math.max(1,...statistics.statusRows.map(item=>item.count))
  return <div className="space-y-7"><PageHeader eyebrow="Seguimiento operativo" title="Estadísticas" description="Lectura descriptiva de sesiones y cuestionarios registrados. No aplica normas clínicas, diagnósticos ni recomendaciones automáticas." actions={<><label className="grid gap-1 text-[10px] font-black uppercase tracking-[.12em] text-[#71878c]">Paciente<select value={patientId} onChange={event=>setPatientId(event.target.value)} className="h-11 min-w-48 rounded-2xl border border-[#dce7e5] bg-white px-3 text-xs font-bold normal-case tracking-normal text-[#29474d]"><option value="">Todos</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.fullName}</option>)}</select></label><label className="grid gap-1 text-[10px] font-black uppercase tracking-[.12em] text-[#71878c]">Período<select value={period} onChange={event=>setPeriod(event.target.value as StatisticsPeriod)} className="h-11 rounded-2xl border border-[#dce7e5] bg-white px-3 text-xs font-bold normal-case tracking-normal text-[#29474d]"><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option><option value="all">Todo el historial</option></select></label></>}/>
    {pending?<div className="grid min-h-64 place-items-center rounded-3xl border border-[#dce7e5] bg-white text-sm font-bold text-[#71878c]">Calculando estadísticas…</div>:<>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={MonitorPlay} label="Sesiones del período" value={String(statistics.totals.sessions)} detail={`${statistics.modes.home} domiciliarias · ${statistics.modes.inPerson} presenciales`} tone="blue"/><StatCard icon={CheckCircle2} label="Registradas como realizadas" value={`${statistics.totals.realizationRate}%`} detail={`${statistics.totals.completed} completas · ${statistics.totals.partial} parciales`}/><StatCard icon={Clock3} label="Tiempo activo" value={`${statistics.totals.activeMinutes} min`} detail={statistics.totals.averageActiveProgress===null?'Sin ejecuciones con duración':'Promedio '+statistics.totals.averageActiveProgress+'% del tiempo planificado'} tone="amber"/><StatCard icon={ClipboardList} label="Cuestionarios" value={String(statistics.totals.evaluations)} detail={`${statistics.totals.completeEvaluations} transcripciones completas`} tone="rose"/></section>
      <aside className="rounded-2xl border border-[#bcded9] bg-[#e8f5f2] px-5 py-4 text-xs leading-5 text-[#3e716f]"><strong className="text-[#075e5a]">Cómo leer este tablero:</strong> “realizada” agrupa sesiones completas y parciales. Los porcentajes describen registros de ONUr; no miden recuperación, eficacia terapéutica ni condición clínica.</aside>
      <section className="grid gap-6 xl:grid-cols-2"><article className="rounded-3xl border border-[#dce7e5] bg-white p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#eaf1f8] text-[#35658a]"><BarChart3 size={18}/></span><div><h2 className="text-lg font-black text-[#123238]">Actividad por mes</h2><p className="text-xs text-[#71878c]">Asignadas frente a registradas como realizadas</p></div></div>{statistics.activityByMonth.length===0?<p className="mt-6 rounded-2xl bg-[#f5f8f7] p-5 text-sm text-[#71878c]">No hay sesiones en el período elegido.</p>:<div className="mt-6 flex h-52 items-end gap-3 border-b border-[#dce7e5] pb-2">{statistics.activityByMonth.map(item=><div key={item.key} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div className="flex h-36 w-full items-end justify-center gap-1"><span title={`${item.assigned} asignadas`} className="w-3 max-w-[28%] rounded-t bg-[#cbdad7]" style={{height:`${Math.max(7,item.assigned/maxMonthly*100)}%`}}/><span title={`${item.realized} realizadas`} className="w-3 max-w-[28%] rounded-t bg-[#0b7a75]" style={{height:`${Math.max(item.realized?7:0,item.realized/maxMonthly*100)}%`}}/></div><span className="truncate text-[10px] font-bold capitalize text-[#71878c]">{item.label}</span></div>)}</div>}<div className="mt-4 flex gap-5 text-[10px] font-bold text-[#60777d]"><span className="flex items-center gap-2"><i className="size-2.5 rounded-sm bg-[#cbdad7]"/>Asignadas</span><span className="flex items-center gap-2"><i className="size-2.5 rounded-sm bg-[#0b7a75]"/>Realizadas</span></div></article>
        <article className="rounded-3xl border border-[#dce7e5] bg-white p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#e8f5f2] text-[#0b7a75]"><CheckCircle2 size={18}/></span><div><h2 className="text-lg font-black text-[#123238]">Estado de las sesiones</h2><p className="text-xs text-[#71878c]">Conteo sin asignaciones revocadas</p></div></div>{statistics.statusRows.length===0?<p className="mt-6 rounded-2xl bg-[#f5f8f7] p-5 text-sm text-[#71878c]">No hay estados para mostrar.</p>:<div className="mt-6 space-y-4">{statistics.statusRows.map(item=><div key={item.status}><div className="flex justify-between text-xs"><span className="font-bold text-[#526a70]">{statusLabels[item.status]}</span><strong className="text-[#123238]">{item.count}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#edf2f1]"><div className="h-full rounded-full bg-[#0b7a75]" style={{width:`${item.count/maxStatus*100}%`}}/></div></div>)}</div>}</article></section>
      <section className="overflow-hidden rounded-3xl border border-[#dce7e5] bg-white"><div className="flex items-center justify-between border-b border-[#e8efed] p-6"><div><h2 className="text-lg font-black text-[#123238]">Resumen por paciente</h2><p className="mt-1 text-xs text-[#71878c]">La variación del cuestionario es matemática, sin interpretación clínica.</p></div><Users size={20} className="text-[#0b7a75]"/></div>{statistics.patientRows.length===0?<p className="p-8 text-sm text-[#71878c]">No hay actividad en el período elegido.</p>:<div className="divide-y divide-[#e8efed]">{statistics.patientRows.map(row=><Link key={row.patientId} to={`/app/pacientes/${row.patientId}`} className="grid gap-3 px-6 py-5 hover:bg-[#f8fbfa] md:grid-cols-[1.4fr_.7fr_.7fr_.7fr_.8fr] md:items-center"><strong className="text-sm text-[#29474d]">{row.patientName}</strong><span className="text-xs text-[#60777d]">{row.realized}/{row.assigned} realizadas</span><span className="text-xs text-[#60777d]">{row.activeMinutes} min activos</span><span className="text-xs text-[#60777d]">{row.realizationRate===null?'—':row.realizationRate+'%'}</span><span className={`text-xs font-black ${row.questionnaireDifference===null?'text-[#9aa8aa]':row.questionnaireDifference>0?'text-[#9a6511]':'text-[#0b7a75]'}`}>{row.questionnaireDifference===null?'Sin par inicial/final':`${row.questionnaireDifference>0?'+':''}${row.questionnaireDifference} puntos`}</span></Link>)}</div>}</section>
      <section className="grid gap-5 lg:grid-cols-[1fr_.75fr]"><article className="rounded-3xl border border-[#dce7e5] bg-white p-6"><h2 className="text-lg font-black text-[#123238]">Comparaciones de percepción</h2><p className="mt-1 text-xs leading-5 text-[#71878c]">Solo pares inicial/final completos del cuestionario ONUr v2, sobre las mismas preguntas aplicables.</p>{statistics.assessmentComparisons.length===0?<p className="mt-5 rounded-2xl bg-[#f5f8f7] p-5 text-sm text-[#71878c]">Todavía no hay pares completos en el período seleccionado.</p>:<div className="mt-5 divide-y divide-[#e8efed]">{statistics.assessmentComparisons.slice(0,8).map(item=><div key={`${item.patientId}-${item.treatmentCycleId}`} className="flex items-center justify-between gap-4 py-4"><div><Link to={`/app/pacientes/${item.patientId}`} className="text-sm font-black text-[#29474d]">{item.patientName}</Link><p className="mt-1 text-xs text-[#71878c]">{item.initialDate} → {item.finalDate} · {item.comparedCount} preguntas</p></div><div className="text-right"><p className="text-sm font-black text-[#123238]">{item.initialTotal} → {item.finalTotal}</p><p className="mt-1 text-xs font-bold text-[#60777d]">{item.difference>0?'+':''}{item.difference} puntos</p></div></div>)}</div>}</article><article className="rounded-3xl border border-[#dce7e5] bg-[#123238] p-6 text-white"><Home size={22} className="text-[#79d8cd]"/><h2 className="mt-5 text-lg font-black">Límites del análisis</h2><ul className="mt-4 space-y-3 text-xs leading-5 text-white/68"><li>• No compara con población normativa.</li><li>• No atribuye cambios al entrenamiento.</li><li>• No reemplaza revisión de estudios o entrevista.</li><li>• No publica sugerencias al paciente.</li></ul></article></section>
    </>}</div>
}
