import { CheckCircle2, FileSearch, Filter, LockKeyhole, Plus, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { StatCard } from '../components/StatCard'
import { StatusBadge } from '../components/StatusBadge'
import { useClinicalStudies } from '../features/studies/hooks'
import type { ClinicalStudyReview, StudyType } from '../features/studies/types'

const typeLabels:Record<StudyType,string>={posturography:'Posturografía',vhit:'vHIT'}

export function StudiesPage(){const{data:studies=[],isPending,error}=useClinicalStudies();const[search,setSearch]=useState('');const[type,setType]=useState<StudyType|''>('');const[status,setStatus]=useState<ClinicalStudyReview['status']|''>('');const filtered=useMemo(()=>{const needle=search.trim().toLocaleLowerCase('es');return studies.filter(item=>(!needle||`${item.patientName} ${item.sourceFilename} ${item.protocolCode}`.toLocaleLowerCase('es').includes(needle))&&(!type||item.studyType===type)&&(!status||item.status===status))},[search,status,studies,type]);return <div className="space-y-7"><PageHeader eyebrow="Registro estructurado" title="Estudios" description="Posturografías y vHIT cargados, revisados o finalizados. Las conclusiones estadísticas permanecen separadas y requieren revisión profesional." actions={<Link to="/app/estudios/importar" className="inline-flex items-center gap-2 rounded-2xl bg-[#0b7a75] px-4 py-3 text-sm font-black text-white"><Plus size={17}/> Importar estudio</Link>}/>
  <section className="grid gap-4 sm:grid-cols-3"><StatCard icon={FileSearch} label="Total" value={String(studies.length)} detail={`${studies.filter(item=>item.studyType==='posturography').length} posturografías · ${studies.filter(item=>item.studyType==='vhit').length} vHIT`} tone="blue"/><StatCard icon={CheckCircle2} label="Revisados" value={String(studies.filter(item=>item.status==='reviewed').length)} detail="Disponibles para finalizar"/><StatCard icon={LockKeyhole} label="Finalizados" value={String(studies.filter(item=>item.status==='finalized').length)} detail="Contenido bloqueado" tone="amber"/></section>
  <section className="rounded-3xl border border-[#dce7e5] bg-white p-4"><div className="grid gap-3 md:grid-cols-[1fr_190px_190px]"><label className="relative"><span className="sr-only">Buscar estudios</span><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#8aa0a4]" size={17}/><input value={search} onChange={event=>setSearch(event.target.value)} className="h-12 w-full rounded-2xl border border-[#dce7e5] pl-11 pr-4 text-sm" placeholder="Buscar paciente, archivo o protocolo"/></label><label className="relative"><Filter className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[#8aa0a4]" size={15}/><select aria-label="Filtrar por tipo" value={type} onChange={event=>setType(event.target.value as StudyType|'')} className="h-12 w-full rounded-2xl border border-[#dce7e5] bg-white pl-9 pr-3 text-xs font-bold text-[#526a70]"><option value="">Todos los tipos</option><option value="posturography">Posturografía</option><option value="vhit">vHIT</option></select></label><select aria-label="Filtrar por estado" value={status} onChange={event=>setStatus(event.target.value as ClinicalStudyReview['status']|'')} className="h-12 rounded-2xl border border-[#dce7e5] bg-white px-3 text-xs font-bold text-[#526a70]"><option value="">Todos los estados</option><option value="draft">Borrador</option><option value="reviewed">Revisado</option><option value="finalized">Finalizado</option></select></div></section>
  <section className="overflow-hidden rounded-3xl border border-[#dce7e5] bg-white"><div className="hidden grid-cols-[1.1fr_.8fr_.8fr_.8fr_.6fr] gap-4 bg-[#f8faf9] px-6 py-3 text-[10px] font-black uppercase tracking-[.12em] text-[#71878c] md:grid"><span>Paciente / estudio</span><span>Fecha</span><span>Protocolo</span><span>Datos</span><span>Estado</span></div>{isPending?<p className="p-8 text-sm text-[#71878c]">Cargando estudios…</p>:error?<p role="alert" className="p-8 text-sm font-bold text-[#a94952]">{error instanceof Error?error.message:'No fue posible cargar los estudios.'}</p>:filtered.length===0?<p className="p-8 text-sm text-[#71878c]">No hay estudios que coincidan con los filtros.</p>:<div className="divide-y divide-[#e8efed]">{filtered.map(item=><Link key={item.id} to={`/app/estudios/${item.id}/revisar`} className="grid gap-3 px-6 py-5 hover:bg-[#f8fbfa] md:grid-cols-[1.1fr_.8fr_.8fr_.8fr_.6fr] md:items-center"><div><p className="text-sm font-black text-[#29474d]">{item.patientName}</p><p className="mt-1 truncate text-xs text-[#71878c]">{typeLabels[item.studyType]} · {item.sourceFilename}</p></div><span className="text-xs text-[#60777d]">{item.performedAt.slice(0,10)}</span><span className="text-xs text-[#60777d]">{item.protocolCode} · v{item.protocolVersion}</span><span className="text-xs text-[#60777d]">{item.metricCount} métricas · {item.issueCount} incidencias</span><StatusBadge status={item.status}/></Link>)}</div>}</section>
  <p className="text-xs leading-5 text-[#71878c]">“Finalizado” describe la integridad del registro. No significa validación diagnóstica ni interpretación clínica automática.</p></div>}
