import { ChevronLeft } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { usePatient } from '../features/patients/hooks'
import { useCreateTreatmentCycle } from '../features/sessions/hooks'
import { cycleFormSchema, type CycleFormValues } from '../features/sessions/schema'

export function TreatmentCycleFormPage(){
  const {patientId=''}=useParams();const navigate=useNavigate();const {data:patient}=usePatient(patientId);const create=useCreateTreatmentCycle(patientId)
  const [values,setValues]=useState<CycleFormValues>({label:'Ciclo 1',reason:'',objectives:'',startedOn:new Date().toISOString().slice(0,10)});const[errors,setErrors]=useState<Record<string,string>>({})
  const submit=async(event:FormEvent)=>{event.preventDefault();const parsed=cycleFormSchema.safeParse(values);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(issue=>[String(issue.path[0]),issue.message])));return}try{await create.mutateAsync(parsed.data);navigate(`/app/pacientes/${patientId}`,{state:{notice:'Ciclo de tratamiento iniciado.'}})}catch(caught){setErrors({form:caught instanceof Error?caught.message:'No fue posible crear el ciclo.'})}}
  const input='mt-2 h-12 w-full rounded-2xl border border-[#E9E7E7] bg-white px-4 text-sm text-[#171717]'
  return <div className="mx-auto max-w-3xl space-y-7"><Link to={`/app/pacientes/${patientId}`} className="inline-flex items-center gap-2 text-xs font-black text-[#E49A02]"><ChevronLeft size={16}/> Volver al perfil</Link><PageHeader eyebrow="Plan de atención" title="Iniciar ciclo de tratamiento" description={patient?`Nuevo ciclo para ${patient.fullName}. El ciclo anterior se pausará si todavía está activo.`:'Definí el punto de partida del tratamiento.'}/><form onSubmit={submit} className="space-y-5 rounded-2xl border border-[#E9E7E7] bg-white p-6 sm:p-8"><label className="block text-sm font-black text-[#2F2F2F]">Nombre del ciclo *<input className={input} value={values.label} onChange={e=>setValues(v=>({...v,label:e.target.value}))}/>{errors.label&&<small className="text-[#a94952]">{errors.label}</small>}</label><label className="block text-sm font-black text-[#2F2F2F]">Fecha de inicio *<input type="date" className={input} value={values.startedOn} onChange={e=>setValues(v=>({...v,startedOn:e.target.value}))}/></label><label className="block text-sm font-black text-[#2F2F2F]">Motivo o contexto<textarea className="mt-2 min-h-24 w-full rounded-2xl border border-[#E9E7E7] p-4 text-sm" value={values.reason} onChange={e=>setValues(v=>({...v,reason:e.target.value}))}/></label><label className="block text-sm font-black text-[#2F2F2F]">Objetivos profesionales<textarea className="mt-2 min-h-28 w-full rounded-2xl border border-[#E9E7E7] p-4 text-sm" value={values.objectives} onChange={e=>setValues(v=>({...v,objectives:e.target.value}))}/><small className="mt-1 block font-normal text-[#747474]">Información privada; no se muestra automáticamente al paciente.</small></label>{errors.form&&<p role="alert" className="rounded-2xl bg-[#fceced] p-4 text-sm font-bold text-[#a94952]">{errors.form}</p>}<button disabled={create.isPending} className="w-full rounded-2xl bg-[#E49A02] px-5 py-4 text-sm font-black text-white">{create.isPending?'Creando ciclo…':'Iniciar ciclo'}</button></form></div>
}
