import { isSupabaseConfigured, supabase } from '../../lib/supabase'

export interface PortalAccountRecord {patientId:string;username:string;enabled:boolean;mustChangePin:boolean;failedAttempts:number;lockedUntil:string;lastLoginAt:string}
export type AccountAction='enable'|'disable'|'unlock'|'reset_temporary_secret'
const STORAGE_KEY='onur-demo-portal-accounts-v1'
const seed:PortalAccountRecord[]=[{patientId:'ana-p',username:'anapereira',enabled:true,mustChangePin:false,failedAttempts:0,lockedUntil:'',lastLoginAt:'2026-07-16T09:20:00.000Z'},{patientId:'luis-s',username:'luissilva',enabled:true,mustChangePin:false,failedAttempts:0,lockedUntil:'',lastLoginAt:''}]
function read(){const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return seed;try{return JSON.parse(raw) as PortalAccountRecord[]}catch{return seed}}
function write(items:PortalAccountRecord[]){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
function fromRow(row:Record<string,unknown>):PortalAccountRecord{return{patientId:String(row.patient_id),username:String(row.username_normalized),enabled:Boolean(row.enabled),mustChangePin:Boolean(row.must_change_pin),failedAttempts:Number(row.failed_attempts??0),lockedUntil:String(row.locked_until??''),lastLoginAt:String(row.last_login_at??'')}}
export async function getPortalAccount(patientId:string):Promise<PortalAccountRecord|null>{if(!isSupabaseConfigured||!supabase)return read().find(item=>item.patientId===patientId)??null;const{data,error}=await supabase.from('patient_portal_accounts').select('patient_id, username_normalized, enabled, must_change_pin, failed_attempts, locked_until, last_login_at').eq('patient_id',patientId).maybeSingle();if(error)throw error;return data?fromRow(data):null}
export async function createPortalAccount(patientId:string,username:string,temporaryCi:string):Promise<void>{if(!isSupabaseConfigured||!supabase){write([...read().filter(item=>item.patientId!==patientId),{patientId,username:username.toLowerCase(),enabled:true,mustChangePin:true,failedAttempts:0,lockedUntil:'',lastLoginAt:''}]);return}const{error}=await supabase.functions.invoke('create-patient-account',{body:{patient_id:patientId,username,temporary_ci:temporaryCi}});if(error)throw error}
export async function managePortalAccount(patientId:string,action:AccountAction,temporaryCi=''):Promise<void>{if(!isSupabaseConfigured||!supabase){write(read().map(item=>item.patientId===patientId?{...item,enabled:action==='disable'?false:action==='enable'||action==='reset_temporary_secret'?true:item.enabled,mustChangePin:action==='reset_temporary_secret'?true:item.mustChangePin,failedAttempts:action==='unlock'||action==='reset_temporary_secret'?0:item.failedAttempts,lockedUntil:action==='unlock'||action==='reset_temporary_secret'?'':item.lockedUntil}:item));return}const{error}=await supabase.functions.invoke('manage-patient-account',{body:{patient_id:patientId,action,temporary_ci:temporaryCi}});if(error)throw error}
